[package]
name = "nym-vpn-api-lib-wasm"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bs58 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
time = { workspace = true, features = ["wasm-bindgen"] }
thiserror.workspace = true
zeroize = { workspace = true }

# wasm-specific deps
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = { workspace = true }
js-sys = "0.3.70"
tsify = { workspace = true, features = ["js"] }
serde-wasm-bindgen = "0.6.5"

# NYM:
nym-bin-common = { workspace = true }
nym-crypto = { workspace = true, features = ["asymmetric"] }
nym-compact-ecash = { workspace = true }
nym-credentials = { workspace = true }
nym-credentials-interface = { workspace = true }
nym-ecash-time = { workspace = true, features = ["expiration"] }
nym-vpn-api-requests = { path = "../vpn-api-requests", default-features = false, features = ["tsify"] }
wasm-utils = { workspace = true }

