[profile.release]
panic = "abort"
opt-level = "s"
overflow-checks = true

[profile.dev]
panic = "abort"

[workspace]

resolver = "2"
members = [
    "vpn-api-server",
    "vpn-api-requests",
    "vpn-api-lib-wasm"
]

[workspace.package]
authors = ["Nym Technologies SA"]
repository = "https://github.com/nymtech/nym"
homepage = "https://nymtech.net"
documentation = "https://nymtech.net"
edition = "2021"
license = "GPL-3.0"

[workspace.dependencies]
async-trait = "0.1.80"
axum = "0.7.5"
anyhow = "1.0.71"
bip39 = "2.0.0"
bs58 = "0.5.1"
colored = "2.1.0"
cfg-if = "1.0.0"
clap = "4.5.4"
dotenv = "0.15.0"
futures = "0.3.30"
humantime = "2.1.0"
thiserror = "1.0.59"
rand = "0.8.5"
reqwest = "0.12.4"
schemars = "0.8.17"
strum = "0.26.3"
strum_macros = "0.26.4"
serde = "1.0.200"
serde_json = "1.0.117"
sqlx = "0.7.4"
tempfile = "3.12.0"
time = "0.3.36"
tracing = "0.1.40"
tsify = "0.4.5"
tokio = "1.37.0"
tokio-util = "0.7.10"
tower = "0.5.0"
tower-http = "0.5.2"
uuid = "1.8.0"
url = "2.5.2"
utoipa = "4.2.0"
utoipa-swagger-ui = "7.0.1"
zeroize = "1.6.0"

wasm-bindgen = "0.2.93"
wasmtimer = "0.2.0"


# point to the current head of `feature/ticketbook-utils` (as of 30.08.2024)
nym-bin-common = { git = "https://github.com/nymtech/nym", rev = "6dee57fc46fa30420510ef7d8b7100607762fe3e" }
nym-crypto = { git = "https://github.com/nymtech/nym", rev = "6dee57fc46fa30420510ef7d8b7100607762fe3e" }
nym-config = { git = "https://github.com/nymtech/nym", rev = "6dee57fc46fa30420510ef7d8b7100607762fe3e" }
nym-http-api-common = { git = "https://github.com/nymtech/nym", rev = "6dee57fc46fa30420510ef7d8b7100607762fe3e" }
nym-http-api-client = { git = "https://github.com/nymtech/nym", rev = "6dee57fc46fa30420510ef7d8b7100607762fe3e" }
nym-credentials = { git = "https://github.com/nymtech/nym", rev = "6dee57fc46fa30420510ef7d8b7100607762fe3e" }
nym-credentials-interface = { git = "https://github.com/nymtech/nym", rev = "6dee57fc46fa30420510ef7d8b7100607762fe3e" }
nym-validator-client = { git = "https://github.com/nymtech/nym", rev = "6dee57fc46fa30420510ef7d8b7100607762fe3e" }
nym-network-defaults = { git = "https://github.com/nymtech/nym", rev = "6dee57fc46fa30420510ef7d8b7100607762fe3e" }
nym-api-requests = { git = "https://github.com/nymtech/nym", rev = "6dee57fc46fa30420510ef7d8b7100607762fe3e" }
nym-serde-helpers = { git = "https://github.com/nymtech/nym", rev = "6dee57fc46fa30420510ef7d8b7100607762fe3e" }
wasm-utils = { git = "https://github.com/nymtech/nym", rev = "6dee57fc46fa30420510ef7d8b7100607762fe3e" }
nym-compact-ecash = { git = "https://github.com/nymtech/nym", rev = "6dee57fc46fa30420510ef7d8b7100607762fe3e" }
nym-ecash-time = { git = "https://github.com/nymtech/nym", rev = "6dee57fc46fa30420510ef7d8b7100607762fe3e" }


## point to local files instead; makes it easier to debug issues
#[patch.'https://github.com/nymtech/nym']
#nym-bin-common = { path = "../nym/common/bin-common" }
#nym-crypto = { path = "../nym/common/crypto" }
#nym-config = { path = "../nym/common/config" }
#nym-http-api-common = { path = "../nym/common/http-api-common" }
#nym-http-api-client = { path = "../nym/common/http-api-client" }
#nym-credentials = { path = "../nym/common/credentials" }
#nym-credentials-interface = { path = "../nym/common/credentials-interface" }
#nym-validator-client = { path = "../nym/common/client-libs/validator-client" }
#nym-network-defaults = { path = "../nym/common/network-defaults" }
#nym-api-requests = { path = "../nym/nym-api/nym-api-requests" }
#nym-serde-helpers = { path = "../nym/common/serde-helpers" }
#wasm-utils = { path = "../nym/common/wasm/utils" }
#nym-compact-ecash = { path = "../nym/common/nym_offline_compact_ecash" }
#nym-ecash-time = { path = "../nym/common/ecash-time" }
